language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t startx88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true startx88/react-test npm test -- --coverage

after_success:
  - docker build -t startx88/theposts-client ./client
  - docker build -t startx88/theposts-nginx  ./nginx
  - docker build -t startx88/theposts-server ./server
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to the docker hub
  - docker push startx88/theposts-client
  - docker push startx88/theposts-nginx
  - docker push startx88/theposts-server
