version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "5000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DATABASE= theposts
      - USER_NAME= root
      - PASSWORD= example
      - PORT= 4200
      - SECRET_KEY= ilovedockerapplication
    depends_on:
      - mongo
  client:
    stdin_open: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
